feature: isolated bootstrapping and style configs
wolf-gmbh/service-blueprints-frontend-vite-reactjs-blueprint pull request #5
Opened 2023-09-27 14:04 UTC by sdrewergutland

2023-09-27 14:05 UTC, johannesdold approved these changes

2023-09-28 06:48 UTC, mahmonirbkh approved these changes

2023-09-28 06:58 UTC, johannesdold requested changes

2023-09-28 06:58 UTC, johannesdold commented on Makefile
> +	read -p "Enter new package/project name:" package_name;\
Please add a @ before the read command, so that the output to the user is more clear.

2023-09-28 06:58 UTC, johannesdold commented on Makefile
> +		--volume "$$PACKAGE_DIR":/workspace/$$package_name \
Please add the option -u node here, so that the files are created with user 1000:1000 and do not belong to root on the host system.

2023-09-28 08:57 UTC, johannesdold approved these changes

2023-09-28 11:59 UTC, merged